--!strict
-- Arbre n°1 — payé en golds, RESET COMPLET au prestige (sauf nœud Mémoire d'Arbre dans l'arbre prestige)
-- Coût du niveau N = costLevel1 × costMult ^ (N - 1)
return {
	DegatsI = {
		displayName = "Dégâts I",
		effect = "Dégâts +5% par niveau",
		maxLevel = 10,
		costLevel1 = 500,
		costMult = 1.6,
		requires = nil,
	},
	GainsI = {
		displayName = "Gains I",
		effect = "Golds +5% par niveau",
		maxLevel = 10,
		costLevel1 = 500,
		costMult = 1.6,
		requires = nil,
	},
	LuckI = {
		displayName = "Luck I",
		effect = "Luck +10% par niveau",
		maxLevel = 10,
		costLevel1 = 2000,
		costMult = 1.8,
		requires = nil,
	},
	EquipeBonus = {
		displayName = "Équipe +1",
		effect = "+1 emplacement de pet équipé",
		maxLevel = 3,
		costLevel1 = 50000,
		costMult = 6,
		requires = { node = "DegatsI", level = 5 },
	},
	RollRapide = {
		displayName = "Roll Rapide",
		effect = "Vitesse de roll +10% par niveau",
		maxLevel = 5,
		costLevel1 = 10000,
		costMult = 2,
		requires = { node = "LuckI", level = 3 },
	},
	AutoRoll = {
		displayName = "Auto-Roll",
		effect = "Débloque le roll automatique",
		maxLevel = 1,
		costLevel1 = 200000,
		costMult = 1,
		requires = { node = "RollRapide", level = 5 },
	},
	DegatsII = {
		displayName = "Dégâts II",
		effect = "Dégâts +8% par niveau",
		maxLevel = 10,
		costLevel1 = 100000,
		costMult = 1.8,
		requires = { node = "DegatsI", level = 10 },
	},
	GainsII = {
		displayName = "Gains II",
		effect = "Golds +8% par niveau",
		maxLevel = 10,
		costLevel1 = 100000,
		costMult = 1.8,
		requires = { node = "GainsI", level = 10 },
	},
	LuckII = {
		displayName = "Luck II",
		effect = "Luck +15% par niveau",
		maxLevel = 10,
		costLevel1 = 500000,
		costMult = 2,
		requires = { node = "LuckI", level = 10 },
	},
	MultiRollX3 = {
		displayName = "Multi-Roll x3",
		effect = "Roll 3 œufs à la fois",
		maxLevel = 1,
		costLevel1 = 1000000,
		costMult = 1,
		requires = { node = "AutoRoll", level = 1 },
	},
}
